### ISSUE TITLE
Build fails on Travis with: unable to load standard library for target 'armv7-apple-ios8.0-simulator

### ISSUE THREAD

**Issue by phranck** [Alamofire/Alamofire#2612]
We switched our project to Xcode 10 with Swift 4.2, and so we does for our `.travis.yml`. But Travis fails on building when it comes to Alamofire. I started a debug build and had a look into the log file. It says:

```
<unknown>:0: error: unable to load standard library for target 'armv7-apple-ios8.0-simulator'

** ARCHIVE FAILED **

The following build commands failed:
        CompileSwift normal arm64
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
        CompileSwift normal armv7
        CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
(4 failures)
```
I think this `ios8.0-simulator` is a result of Alamofire's deployment target of iOS 8.0.

So, now I'm struggling a bit of how to investigate if it's an issue with Travis or Alamofire itself.  
Our `.travis.yml` looks like this:

```
language: objective-c
osx_image: xcode10

cache:
  directories:
    - Carthage
    - CookIslands/Carthage

env:
  #environment variables
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - PROJECT_NAME="OUR_PROJECT.xcodeproj"
    - SCHEME_IOS_FRAMEWORK="OUR_FRAMEWORK_iOS"
    - SCHEME_IOS="OUR_SCHEME"
    - IOS_SDK=iphonesimulator12.0
  matrix:
    - DESTINATION="OS=12.0,name=iPhone X" SCHEME="$SCHEME_IOS" SDK="$IOS_SDK"

before_install:
  - brew update
  - brew upgrade carthage || true
  - git submodule update --remote
  - gem install license_finder

script:
  - xcodebuild test -project "$PROJECT_NAME" -scheme "$SCHEME" -destination "$DESTINATION" -sdk "$SDK" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
```

Is there any issue known with Xcode 10, Swift 4.2, Alamofire 4.7.3 using Travis?

## Alamofire Environment

**Alamofire version:** 4.7.3  
**Xcode version:** 10  
**Swift version:** 4.2  
**Platform(s) running Alamofire:**  iOS 12, tvOS 12
**macOS version running Xcode:** Mojave
